---
name: CI

on:
  workflow_dispatch:
    inputs:
      revision:
        description: 'The revision to run CI on.'
        required: false
        default: main
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: read

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.revision }}

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: Run format checks
        if: success() || failure()
        run: 'yarn format:check'

      - name: Run linter
        if: success() || failure()
        run: 'yarn lint:check'

      - name: Run tests
        if: success() || failure()
        env:
          NODE_ENV: test
        run: 'yarn test:ci'
