---
name: Format CODEOWNERS

on:
  workflow_dispatch:
    inputs:
      format-style:
        description: 'The style of format to apply.'
        required: true
        default: 'lined-up'
        type: choice
        options:
          - 'lined-up'
          - 'one-space'
      file-path:
        description: |
          Optional. The path to the CODEOWNERS file to operate on.
          Otherwise searches for valid CODEOWNERS files in the repository.
        required: false
        default: .github/CODEOWNERS
        type: string

permissions:
  contents: write

jobs:
  format-codeowners:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./
        id: format-codeowners
        with:
          format-style: ${{ github.event.inputs.format-style }}
          file-path: ${{ github.event.inputs.file-path }}

      - uses: stefanzweifel/git-auto-commit-action@v4
        if: steps.format-codeowners.outputs.formatted-files != ''
        with:
          commit_message: Reformat CODEOWNERS
          commit_options: '--no-verify --signoff'
          file_pattern: ${{ steps.format-codeowners.outputs.formatted-files }}
          disable_globbing: true
